### ISSUE TITLE
Does not correctly import projects with custom scala toolchain

### ISSUE THREAD

**Issue by liucijus** [JetBrains/bazel-bsp#127]
bazel-bsp fails on projects with custom [Scala Toolchain](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_toolchain.md) which has custom dependency providers

Example project: https://github.com/liucijus/rules-scala-proto-toolchain/

Exception in Intellij build window:
```
Command aborted with reason LOADING_FAILURE: no such package '@io_bazel_rules_scala_scala_library//': The repository '@io_bazel_rules_scala_scala_library' could not be resolved
Dec 31, 2021 11:26:13 AM io.grpc.internal.SerializingExecutor run

SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@e2202e6

java.lang.RuntimeException: Command aborted with reason LOADING_FAILURE: no such package '@io_bazel_rules_scala_scala_library//': The repository '@io_bazel_rules_scala_scala_library' could not be resolved

	at org.jetbrains.bsp.bazel.server.bep.BepServer.consumeAbortedEvent(BepServer.java:246)

	at org.jetbrains.bsp.bazel.server.bep.BepServer.processAbortedEvent(BepServer.java:235)

	at org.jetbrains.bsp.bazel.server.bep.BepServer.handleEvent(BepServer.java:107)

	at org.jetbrains.bsp.bazel.server.bep.BepStreamObserver.onNext(BepStreamObserver.java:28)

	at org.jetbrains.bsp.bazel.server.bep.BepStreamObserver.onNext(BepStreamObserver.java:9)

	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)

	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)

	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)

	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
```

**Comment by odisseus** [comment]
Looks like the BSP server [assumes](https://github.com/JetBrains/bazel-bsp/blob/25d1d48161243a771a7273c7fc7a39ae4ca5872e/server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspScalaTargetManager.java#L40) that the [standard Scala library target](https://github.com/JetBrains/bazel-bsp/blob/25d1d48161243a771a7273c7fc7a39ae4ca5872e/server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspScalaTargetManager.java#L19) always exists. I'm already working to fix this.

**Comment by liucijus** [comment]
> ```
> load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
> 
> scala_repositories(fetch_sources = True)
> ```
> 
> before toolchain registration got me further than that in a similar situation.

It may get further, but it brings different versions of Scala libraries to the project, which is undesired.

**Comment by abrams27** [comment]
https://github.com/JetBrains/bazel-bsp/pull/147 fixes it - the import is now successful
