### ISSUE TITLE
BSP server fails with an unclear message when there's no aspects.bzl in .bazelbsp folder

### ISSUE THREAD

**Issue by agluszak** [JetBrains/bazel-bsp#52]
```
Analyzing: target //:java_deps (0 packages loaded, 0 targets configured)
ERROR: Label '//.bazelbsp:aspects.bzl' is invalid because '.bazelbsp' is not a package; perhaps you meant to put the colon here: '//:.bazelbsp/aspects.bzl'?
ERROR: Analysis of aspect '//.bazelbsp:aspects.bzl%print_aspect of //:java_deps' failed; build aborted: Label '//.bazelbsp:aspects.bzl' is invalid because '.bazelbsp' is not a package; perhaps you meant to put the colon here: '//:.bazelbsp/aspects.bzl'?
INFO: Elapsed time: 204.997s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
Command aborted with reason INCOMPLETE:
kwi 06, 2021 3:58:19 PM io.grpc.internal.SerializingExecutor run

SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@4bfef24a

java.lang.RuntimeException: Command aborted with reason INCOMPLETE: 

	at org.jetbrains.bsp.bazel.server.bep.BepServer.consumeAbortedEvent(BepServer.java:237)

	at org.jetbrains.bsp.bazel.server.bep.BepServer.processAbortedEvent(BepServer.java:226)

	at org.jetbrains.bsp.bazel.server.bep.BepServer.handleEvent(BepServer.java:103)

	at org.jetbrains.bsp.bazel.server.bep.BepStreamObserver.onNext(BepStreamObserver.java:28)

	at org.jetbrains.bsp.bazel.server.bep.BepStreamObserver.onNext(BepStreamObserver.java:9)

	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)

	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)

	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)

	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

	at java.base/java.lang.Thread.run(Thread.java:832)



Command aborted with reason INCOMPLETE:
kwi 06, 2021 3:58:20 PM io.grpc.internal.SerializingExecutor run

SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@5118182b

java.lang.RuntimeException: Command aborted with reason INCOMPLETE: 

	at org.jetbrains.bsp.bazel.server.bep.BepServer.consumeAbortedEvent(BepServer.java:237)

	at org.jetbrains.bsp.bazel.server.bep.BepServer.processAbortedEvent(BepServer.java:226)

	at org.jetbrains.bsp.bazel.server.bep.BepServer.handleEvent(BepServer.java:103)

	at org.jetbrains.bsp.bazel.server.bep.BepStreamObserver.onNext(BepStreamObserver.java:28)

	at org.jetbrains.bsp.bazel.server.bep.BepStreamObserver.onNext(BepStreamObserver.java:9)

	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)

	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)

	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)

	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by abrams27** [comment]
now it shows:
```
ERROR: cannot load '//.bazelbsp:aspects.bzl': no such file
ERROR: cannot load '//.bazelbsp:aspects.bzl': no such file
INFO: Analyzed 95 targets (0 packages loaded, 0 targets configured).
INFO: Found 95 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.301s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

for me its fine, but maybe we should print more informative message - like **"`.bazelbsp` dir doesn't contain all required files - please install server"**

**Comment by abrams27** [comment]
moved to: https://youtrack.jetbrains.com/issue/BAZEL-37
