### ISSUE TITLE
"Invalid version format" when using Bazel rolling releases

### ISSUE THREAD

**Issue by philwo** [JetBrains/bazel-bsp#92]
Hi,

I tried to use the Bazel BSP feature in IntellIJ IDEA 2021.2.1 (UE) with Scala plugin 2021.2.17 and Bazel itself as the project. 

When I use Bazel rolling releases, the plug-in crashes with an "Invalid version format" exception in this line: https://github.com/JetBrains/bazel-bsp/blob/dev/bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/data/SemanticVersion.java#L34

I think this is because the regex used rejects the version number. Maybe you could use the regex given in the SemVer 2.0 spec to parse the string instead? See: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

Details:

```
$ export USE_BAZEL_VERSION=rolling
$ bazel version
Bazelisk version: development
Build label: 5.0.0-pre.20210817.2
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 25 11:16:44 2021 (1629890204)
Build timestamp: 1629890204
Build timestamp as int: 1629890204
```

Stack trace:

```
java.lang.IllegalArgumentException: Invalid version format
	at org.jetbrains.bsp.bazel.server.bazel.data.SemanticVersion.<init>(SemanticVersion.java:34)
	at org.jetbrains.bsp.bazel.server.bazel.data.SemanticVersion.fromReleaseData(SemanticVersion.java:56)
	at org.jetbrains.bsp.bazel.server.bazel.data.BazelData.<init>(BazelData.java:21)
	at org.jetbrains.bsp.bazel.server.bazel.BazelDataResolver.resolveBazelData(BazelDataResolver.java:30)
	at org.jetbrains.bsp.bazel.server.BazelBspServer.<init>(BazelBspServer.java:48)
	at org.jetbrains.bsp.bazel.server.ServerInitializer.main(ServerInitializer.java:49)
```

**Comment by philwo** [comment]
Example of the current regex not fully matching the version number of Bazel rolling releases: https://regex101.com/r/ODrInw/1

Example of the official SemVer regex correctly matching it: https://regex101.com/r/sIqC4o/1/
